### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by sylvainmetayer** [groupe-edf/nexus-report-plugin#29]
Hi, 

Thanks for your plugin, which seems to do exactly what I was looking for ! I'm trying to install it but I'm facing an issue during the installation phase. I've put the release kar in the `deploy` folder and restarted my nexus instance but got the following errors logs : 

```
2022-02-11 14:23:51,794+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-report-plugin; type=karaf.feature; version="[0.2.1,0.2.1]"; filter:="(&(osgi.identity=nexus-report-plugin)(type=karaf.feature)(version>=0.2.1)(version<=0.2.1))" [caused by: Unable to resolve nexus-report-plugin/0.2.1: missing requirement [nexus-report-plugin/0.2.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-report-plugin; type=osgi.bundle; version="[0.2.1,0.2.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"]]
2022-02-11 14:23:51,794+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
2022-02-11 14:23:51,794+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
2022-02-11 14:23:51,795+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
2022-02-11 14:23:51,795+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
2022-02-11 14:23:51,795+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
2022-02-11 14:23:51,795+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
2022-02-11 14:23:51,795+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
2022-02-11 14:23:51,796+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
2022-02-11 14:23:51,796+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-02-11 14:23:51,796+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-02-11 14:23:51,796+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-02-11 14:23:51,796+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at java.lang.Thread.run(Thread.java:748)
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve nexus-report-plugin/0.2.1: missing requirement [nexus-report-plugin/0.2.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-report-plugin; type=osgi.bundle; version="[0.2.1,0.2.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"]
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	... 12 more
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
2022-02-11 14:23:51,797+0100 ERROR [features-2-thread-1]  *SYSTEM java.lang.Throwable - 	... 13 more
2022-02-11 14:23:51,799+0100 WARN  [fileinstall-/opt/nexus/deploy]  *SYSTEM org.apache.karaf.kar.internal.KarServiceImpl - Unable to install Kar feature nexus-report-plugin/0.2.1
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nexus-report-plugin; type=karaf.feature; version="[0.2.1,0.2.1]"; filter:="(&(osgi.identity=nexus-report-plugin)(type=karaf.feature)(version>=0.2.1)(version<=0.2.1))" [caused by: Unable to resolve nexus-report-plugin/0.2.1: missing requirement [nexus-report-plugin/0.2.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-report-plugin; type=osgi.bundle; version="[0.2.1,0.2.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve nexus-report-plugin/0.2.1: missing requirement [nexus-report-plugin/0.2.1] osgi.identity; osgi.identity=org.sonatype.nexus.plugins.nexus-report-plugin; type=osgi.bundle; version="[0.2.1,0.2.1]"; resolution:=mandatory [caused by: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 12 common frames omitted
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1: missing requirement [org.sonatype.nexus.plugins.nexus-report-plugin/0.2.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.softwarementors.extjs.djn.config.annotations)(version>=3.37.0))"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
	... 13 common frames omitted

```

I'm not a Nexus expert and can't see why a dependency is missing. I'm on a manual installation (not dockerized) without any others plugins. Below is the nexus version informations (I used the `0.2.1` of your plugins which seems to be the one compatible)

```
version | 3.33.0-01
-- | --
edition | OSS
buildRevision | d6966dfb56cc73f77e90c1a0a493d7205b029f36
buildTimestamp | 2021-08-02-2017-39574
```

Thanks in advance for your help !

**Comment by sylvainmetayer** [comment]
This was the issue, it is working fine with version 0.2.0. Thanks for the quick answer !
